
ipMapFile: "demo_files/zones.csv"
pacRoot: "demo_files/pacs"
contactInfo: "NOC Germany"
accessLogFile: "./access.log"
eventLogFile: "./events.log"
# TODO: maxCacheAge < 0 is the same as doAutoRefresh NO
doAutoRefresh: true
maxCacheAge: 3600 # 60x60 > 1h cache age
