ipMapFile: "demo_files/zones.csv"
pacRoot: "demo_files/pacs"
defaultPACFile: "demo_files/pacs/default.pac"
wpadFile: "demo_files/pacs/wpad.dat"
contactInfo: "NOC Germany"
accessLogFile: "./access.log"
eventLogFile: "./events.log"
adminSecret: "change-me"
ignoreMinors: true
port: 8081
# Prometheus metrics configuration
prometheusEnabled: true
prometheusPath: "/metrics"
