name: Go Build, Test, and Publish Release

permissions:
  contents: write

on:
  push:
    branches:
      - '**' # Triggers on pushes to every branch
  pull_request:

jobs:
  build:
    name: Test, Build, and Publish Release
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23 # Ensure you use the appropriate Go version

      # Step 3: Download Go dependencies
      - name: Download Dependencies
        run: go mod tidy


      # Step 4: Run tests
      - name: Run Tests
        run: |
          go test ./... -v

      # Step 5: Build the specific Go application for Linux/AMD64
      - name: Build the Go app
        run: |
          mkdir -p build
          GOOS=linux GOARCH=amd64 go build -o build/pacserver ./cmd/pacserver.go

      # Step 6: Publish Release with Artifact
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }} # Dynamically uses the branch name
          files: build/pacserver # Upload the built binary as the release asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required for authentication
